export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";

export const GET_SCRAPPED_EVENTS_REQUEST = "GET_SCRAPPED_EVENTS_REQUEST";
export const GET_SCRAPPED_EVENTS_SUCCESS = "GET_SCRAPPED_EVENTS_SUCCESS";
export const GET_SCRAPPED_EVENTS_FAIL = "GET_SCRAPPED_EVENTS_FAIL";
