export const CREATE_TEAM_REQUEST = "CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAIL = "CREATE_TEAM_FAIL";

export const GET_MY_TEAMS_REQUEST = "GET_MY_TEAMS_REQUEST";
export const GET_MY_TEAMS_SUCCESS = "GET_MY_TEAMS_SUCCESS";
export const GET_MY_TEAMS_FAIL = "GET_MY_TEAMS_FAIL";

export const GET_TEAM_BY_ID_REQUEST = "GET_TEAM_BY_ID_REQUEST";
export const GET_TEAM_BY_ID_SUCCESS = "GET_TEAM_BY_ID_SUCCESS";
export const GET_TEAM_BY_ID_FAIL = "GET_TEAM_BY_ID_FAIL";

export const GET_FILTER_TEAMS_REQUEST = "GET_FILTER_TEAMS_REQUEST";
export const GET_FILTER_TEAMS_SUCCESS = "GET_FILTER_TEAMS_SUCCESS";
export const GET_FILTER_TEAMS_FAIL = "GET_FILTER_TEAMS_FAIL";

export const GET_TEAMS_FROM_SEARCH_REQUEST = "GET_TEAMS_FROM_SEARCH_REQUEST";
export const GET_TEAMS_FROM_SEARCH_SUCCESS = "GET_TEAMS_FROM_SEARCH_SUCCESS";
export const GET_TEAMS_FROM_SEARCH_FAIL = "GET_TEAMS_FROM_SEARCH_FAIL";

export const SEND_REQUEST_TO_JOIN_TEAM_REQUEST =
  "SEND_REQUEST_TO_JOIN_TEAM_REQUEST";
export const SEND_REQUEST_TO_JOIN_TEAM_SUCCESS =
  "SEND_REQUEST_TO_JOIN_TEAM_SUCCESS";
export const SEND_REQUEST_TO_JOIN_TEAM_FAIL = "SEND_REQUEST_TO_JOIN_TEAM_FAIL";

export const GET_TEAM_REQUESTS_REQUEST = "GET_TEAM_REQUESTS_REQUEST";
export const GET_TEAM_REQUESTS_SUCCESS = "GET_TEAM_REQUESTS_SUCCESS";
export const GET_TEAM_REQUESTS_FAIL = "GET_TEAM_REQUESTS_FAIL";
