export const CREATE_TEAM_REQUEST = "CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAIL = "CREATE_TEAM_FAIL";

export const GET_MY_TEAMS_REQUEST = "GET_MY_TEAMS_REQUEST";
export const GET_MY_TEAMS_SUCCESS = "GET_MY_TEAMS_SUCCESS";
export const GET_MY_TEAMS_FAIL = "GET_MY_TEAMS_FAIL";

export const GET_TEAM_VIEW_REQUEST = "GET_TEAM_REQUEST";
export const GET_TEAM_VIEW_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_VIEW_FAIL = "GET_TEAM_FAIL";

export const GET_FILTER_TEAMS_REQUEST = "GET_FILTER_TEAMS_REQUEST";
export const GET_FILTER_TEAMS_SUCCESS = "GET_FILTER_TEAMS_SUCCESS";
export const GET_FILTER_TEAMS_FAIL = "GET_FILTER_TEAMS_FAIL";

export const GET_TEAMS_FROM_SEARCH_REQUEST = "GET_TEAMS_FROM_SEARCH_REQUEST";
export const GET_TEAMS_FROM_SEARCH_SUCCESS = "GET_TEAMS_FROM_SEARCH_SUCCESS";
export const GET_TEAMS_FROM_SEARCH_FAIL = "GET_TEAMS_FROM_SEARCH_FAIL";
