export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PROFILE_DETAILS_SUCCESS = "USER_PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER_PROFILE_DETAILS_FAIL";
export const USER_PROFILE_DETAILS_RESET = "USER_PROFILE_DETAILS_RESET";

export const GET_BASIC_INFORMATION_SUCCESS = "GET_BASIC_INFORMATION_SUCCESS";
export const GET_BASIC_INFORMATION_FAIL = "GET_BASIC_INFORMATION_FAIL";
