export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PROFILE_DETAILS_REQUEST = "USER_PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER_PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER_PROFILE_DETAILS_FAIL";
export const USER_PROFILE_DETAILS_RESET = "USER_PROFILE_DETAILS_RESET";

export const GET_BASIC_INFORMATION_REQUEST = "GET_BASIC_INFORMATION_REQUEST";
export const GET_BASIC_INFORMATION_SUCCESS = "GET_BASIC_INFORMATION_SUCCESS";
export const GET_BASIC_INFORMATION_FAIL = "GET_BASIC_INFORMATION_FAIL";

export const UPDATE_BASIC_INFORMATION_REQUEST =
  "UPDATE_BASIC_INFORMATION_REQUEST";
export const UPDATE_BASIC_INFORMATION_SUCCESS =
  "UPDATE_BASIC_INFORMATION_SUCCESS";
export const UPDATE_BASIC_INFORMATION_FAIL = "UPDATE_BASIC_INFORMATION_FAIL";

export const GET_SKILLS_REQUEST = "GET_SKILLS_REQUEST";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
export const GET_SKILLS_FAIL = "GET_SKILLS_FAIL";
export const GET_SKILLS_UPDATE_SUCCESS = "GET_SKILLS_UPDATE_SUCCESS";

export const GET_LANGUAGES_REQUEST = "GET_LANGUAGES_REQUEST";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_FAIL = "GET_LANGUAGES_FAIL";
export const GET_LANGUAGES_UPDATE_SUCCESS = "GET_LANGUAGES_UPDATE_SUCCESS";

export const GET_EXPERIENCE_REQUEST = "GET_EXPERIENCE_REQUEST";
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_EXPERIENCE_UPDATE_SUCCESS = "GET_EXPERIENCE_UPDATE_SUCCESS";
export const GET_EXPERIENCE_UPDATE_FAIL = "GET_EXPERIENCE_UPDATE_FAIL";
export const GET_EXPERIENCE_FAIL = "GET_EXPERIENCE_FAIL";

export const GET_EDUCATION_REQUEST = "GET_EDUCATION_REQUEST";
export const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS";
export const GET_EDUCATION_UPDATE_SUCCESS = "GET_EDUCATION_UPDATE_SUCCESS";
export const GET_EDUCATION_UPDATE_FAIL = "GET_EDUCATION_UPDATE_FAIL";
export const GET_EDUCATION_FAIL = "GET_EDUCATION_FAIL";

export const GET_CERTIFICATION_REQUEST = "GET_CERTIFICATION_REQUEST";
export const GET_CERTIFICATION_SUCCESS = "GET_CERTIFICATION_SUCCESS";
export const GET_CERTIFICATION_UPDATE_SUCCESS =
  "GET_CERTIFICATION_UPDATE_SUCCESS";
export const GET_CERTIFICATION_UPDATE_FAIL = "GET_CERTIFICATION_UPDATE_FAIL";
export const GET_CERTIFICATION_FAIL = "GET_CERTIFICATION_FAIL";

export const GET_AWARDS_AND_ACHIEVEMENTS_REQUEST =
  "GET_AWARDS_AND_ACHIEVEMENTS_REQUEST";
export const GET_AWARDS_AND_ACHIEVEMENTS_SUCCESS =
  "GET_AWARDS_AND_ACHIEVEMENTS_SUCCESS";
export const GET_AWARDS_AND_ACHIEVEMENTS_UPDATE_SUCCESS =
  "GET_AWARDS_AND_ACHIEVEMENTS_UPDATE_SUCCESS";
export const GET_AWARDS_AND_ACHIEVEMENTS_UPDATE_FAIL =
  "GET_AWARDS_AND_ACHIEVEMENTS_UPDATE_FAIL";
export const GET_AWARDS_AND_ACHIEVEMENTS_FAIL =
  "GET_AWARDS_AND_ACHIEVEMENTS_FAIL";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_UPDATE_SUCCESS = "GET_PROJECT_UPDATE_SUCCESS";
export const GET_PROJECT_UPDATE_FAIL = "GET_PROJECT_UPDATE_FAIL";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";

export const GET_REQUESTS_REQUEST = "GET_REQUESTS_REQUEST";
export const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";
export const GET_REQUESTS_FAIL = "GET_REQUESTS_FAIL";
